In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [3]:
x_train = torch.FloatTensor([[1], [2],[3]])
y_train = torch.FloatTensor([[1],[2],[3]])

In [4]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [5]:
print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


### Weight Initialization

In [6]:
W = torch.zeros(1, requires_grad = True)
print(W)

tensor([0.], requires_grad=True)


In [7]:
b = torch.zeros(1, requires_grad = True)
print(b)

tensor([0.], requires_grad=True)


### Hypothesis

In [8]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


### Cost

In [9]:
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [10]:
print(y_train)

tensor([[1.],
        [2.],
        [3.]])


In [11]:
print(hypothesis - y_train)

tensor([[-1.],
        [-2.],
        [-3.]], grad_fn=<SubBackward0>)


In [12]:
print((hypothesis-y_train)**2)

tensor([[1.],
        [4.],
        [9.]], grad_fn=<PowBackward0>)


In [13]:
cost = torch.mean((hypothesis - y_train)**2)
print(cost)

tensor(4.6667, grad_fn=<MeanBackward0>)


### Gradient Descent

In [14]:
optimizer = optim.SGD([W,b], lr=0.01)

In [15]:
optimizer.zero_grad()
cost.backward()
optimizer.step()

In [16]:
print(W)
print(b)

tensor([0.0933], requires_grad=True)
tensor([0.0400], requires_grad=True)


In [17]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.1333],
        [0.2267],
        [0.3200]], grad_fn=<AddBackward0>)


In [18]:
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(3.6927, grad_fn=<MeanBackward0>)


### Training with Full Code

In [19]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

W = torch.zeros(1, requires_grad = True)
b = torch.zeros(1, requires_grad = True)
optimizer = optim.SGD([W, b], lr = 0.01)
nb_epochs = 1000

for epoch in range(nb_epochs + 1):
    hypothesis = x_train * W + b
    cost = torch.mean((hypothesis - y_train)**2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print("Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}".format(epoch, nb_epochs, W.item(), b.item(), cost.item()))

Epoch    0/1000 W: 0.093, b: 0.040 Cost: 4.666667
Epoch  100/1000 W: 0.873, b: 0.289 Cost: 0.012043
Epoch  200/1000 W: 0.900, b: 0.227 Cost: 0.007442
Epoch  300/1000 W: 0.921, b: 0.179 Cost: 0.004598
Epoch  400/1000 W: 0.938, b: 0.140 Cost: 0.002842
Epoch  500/1000 W: 0.951, b: 0.110 Cost: 0.001756
Epoch  600/1000 W: 0.962, b: 0.087 Cost: 0.001085
Epoch  700/1000 W: 0.970, b: 0.068 Cost: 0.000670
Epoch  800/1000 W: 0.976, b: 0.054 Cost: 0.000414
Epoch  900/1000 W: 0.981, b: 0.042 Cost: 0.000256
Epoch 1000/1000 W: 0.985, b: 0.033 Cost: 0.000158


## High-level Implementation with nn.Module

In [20]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

In [21]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)
    
    def forward(self, x): # 어떻게 입력값에서 출력값을 계산하는지
        return self.linear(x)

In [22]:
model = LinearRegressionModel()

### Hypothesis

In [23]:
hypothesis = model(x_train)

In [24]:
print(hypothesis)

tensor([[0.0739],
        [0.5891],
        [1.1044]], grad_fn=<AddmmBackward>)


### Cost

In [25]:
print(hypothesis)
print(y_train)

tensor([[0.0739],
        [0.5891],
        [1.1044]], grad_fn=<AddmmBackward>)
tensor([[1.],
        [2.],
        [3.]])


In [26]:
cost = F.mse_loss(hypothesis, y_train)

In [27]:
print(cost)

tensor(2.1471, grad_fn=<MseLossBackward>)


### Gradient Descent

In [28]:
optimizer = optim.SGD(model.parameters(), lr = 0.01)

In [29]:
optimizer.zero_grad()
cost.backward()
optimizer.step()

### Training with Full Code

In [30]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[1],[2],[3]])

mode = LinearRegressionModel()
optimizer = optim.SGD(model.parameters(), lr = 0.01)
nb_epochs = 1000

for epoch in range(nb_epochs + 1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        params = list(model.parameters())
        W = params[0].item()
        b = params[1].item()
        print("Epoch {:4d}/{} W: {:.3f}, b: {:.3f}, Cost: {:.6f}".format(epoch, nb_epochs, W, b, cost.item()))

Epoch    0/1000 W: 0.634, b: -0.388, Cost: 1.698280
Epoch  100/1000 W: 1.066, b: -0.150, Cost: 0.003224
Epoch  200/1000 W: 1.052, b: -0.118, Cost: 0.001992
Epoch  300/1000 W: 1.041, b: -0.092, Cost: 0.001231
Epoch  400/1000 W: 1.032, b: -0.073, Cost: 0.000761
Epoch  500/1000 W: 1.025, b: -0.057, Cost: 0.000470
Epoch  600/1000 W: 1.020, b: -0.045, Cost: 0.000290
Epoch  700/1000 W: 1.016, b: -0.035, Cost: 0.000179
Epoch  800/1000 W: 1.012, b: -0.028, Cost: 0.000111
Epoch  900/1000 W: 1.010, b: -0.022, Cost: 0.000069
Epoch 1000/1000 W: 1.008, b: -0.017, Cost: 0.000042
