In [1]:
import numpy as np

In [3]:
xy = np.loadtxt("D:/torch/data-01-test-score.csv", delimiter=',', dtype=np.float32)

In [4]:
x_data = xy[:, 0:-1]
y_data = xy[:,[-1]]

In [7]:
print(x_data.shape)
print(len(x_data))
print(x_data[:5])

(25, 3)
25
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]


In [8]:
print(y_data.shape)
print(len(y_data))
print(y_data[:5])

(25, 1)
25
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]


In [9]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [10]:
torch.manual_seed(1)

In [11]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

W = torch.zeros((3,1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

optimizer = optim.SGD([W, b], lr = 1e-5)
nb_epochs = 20

for epoch in range(nb_epochs + 1):
    hypothesis = x_train.matmul(W) + b
    cost = F.mse_loss(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print('Epoch {:4d}/{} cost {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/20 cost 26811.960938
Epoch    1/20 cost 9920.531250
Epoch    2/20 cost 3675.298584
Epoch    3/20 cost 1366.260498
Epoch    4/20 cost 512.542480
Epoch    5/20 cost 196.896606
Epoch    6/20 cost 80.190987
Epoch    7/20 cost 37.038692
Epoch    8/20 cost 21.081337
Epoch    9/20 cost 15.178760
Epoch   10/20 cost 12.993677
Epoch   11/20 cost 12.183029
Epoch   12/20 cost 11.880534
Epoch   13/20 cost 11.765964
Epoch   14/20 cost 11.720856
Epoch   15/20 cost 11.701437
Epoch   16/20 cost 11.691510
Epoch   17/20 cost 11.685122
Epoch   18/20 cost 11.680007
Epoch   19/20 cost 11.675373
Epoch   20/20 cost 11.670942


### High-level Implementation with nn.Module

In [12]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)
        
    def forward(self, x):
        return self.linear(x)

In [13]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

model = MultivariateLinearRegressionModel()

optimizer = optim.SGD(model.parameters(), lr = 1e-5)
nb_epochs = 20

for epoch in range(nb_epochs+1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print("Epoch {:4d}/{} cost : {:.6f}".format(epoch, nb_epochs, cost.item()))

Epoch    0/20 cost : 28693.488281
Epoch    1/20 cost : 10618.750000
Epoch    2/20 cost : 3936.015381
Epoch    3/20 cost : 1465.219604
Epoch    4/20 cost : 551.693726
Epoch    5/20 cost : 213.934631
Epoch    6/20 cost : 89.052269
Epoch    7/20 cost : 42.876003
Epoch    8/20 cost : 25.799639
Epoch    9/20 cost : 19.482420
Epoch   10/20 cost : 17.143093
Epoch   11/20 cost : 16.274509
Epoch   12/20 cost : 15.949721
Epoch   13/20 cost : 15.825986
Epoch   14/20 cost : 15.776566
Epoch   15/20 cost : 15.754660
Epoch   16/20 cost : 15.742918
Epoch   17/20 cost : 15.734917
Epoch   18/20 cost : 15.728307
Epoch   19/20 cost : 15.722219
Epoch   20/20 cost : 15.716357
